# required fields
#log_level: DEBUG
api_key: "APIznJxWShGW3Kt"
api_secret: "KEUUtCDVRqXk9me0Ok94g8G9xwtnjMeUxfNMy8dow6iA"
ws_url: "ws://livekit:7880"
insecure: true
redis:
  address: redis:6379
  username: ""
  password: ""
  db: 2
#cpu_cost:
#  room_composite_cpu_cost: 1.0
