logging.level.org.springframework.cloud.gateway.filter: trace

server:
  port: 8282

spring:
#  resources:
#    cache:
#      cachecontrol:
#        no-cache: false
#        max-age: 40s
#    static-locations: file:/home/nkonev/go_1_11/videochat/frontend-nginx/
  sleuth:
    sampler:
      probability: 1.0
      rate: 0
    integration:
      enabled: false
    messaging:
      enabled: false
  application:
    name: gateway
  cloud:
    loadbalancer:
      cache:
        ttl: 30s
      ribbon:
        enabled: false
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: aaa
          predicates:
            - Path=/api/login,/api/logout,/api/profile
          uri: http://localhost:8060
        - id: chat
          predicates:
            - Path=/api/chat/**
          uri: http://localhost:1235
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                methods: GET

aaa.base-url: "http://localhost:8060/internal"
