logLevel = "INFO"
defaultEntryPoints = ["http"]

[api]
entryPoint = "traefik"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http-internal]
  address = ":81"
  [entryPoints.traefik]
  address = ":8080"

[docker]
watch = true
exposedbydefault = false
swarmmode = false

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers]
      [backends.backend1.servers.server0]
        url = "http://video.site.local:10000"


[frontends]
  [frontends.frontend1]
    entryPoints = ["http-internal"]
    backend = "backend1"
    [frontends.frontend1.routes]
      [frontends.frontend1.routes.route0]
        rule = "PathPrefix:/chat"


[tracing]
  backend = "zipkin"
  spanNameLimit = 150

[accessLog]
# Custom headers works only in json format
format = "json"
  [accessLog.filters]

  [accessLog.fields]
  defaultMode = "keep"

  [accessLog.fields.headers]
    defaultMode = "drop"
    # Fields map which is used to override headers defaultMode
    [accessLog.fields.headers.names]
      "User-Agent" = "keep"
      "X-B3-Traceid" = "keep"
