server:
  address: ":1235"
  shutdown.timeout: "10s"
  body.limit: "2M"

http:
  idle:
    conns:
      max: 2
    connTimeout: '10s'
  disableCompression: false

auth:
  exclude:
    - "^/chat/public.*"

postgresql:
  # https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
  url: "postgres://chat:chatPazZw0rd@postgresql:5432/chat?sslmode=disable&application_name=chat-app"
  maxOpenConnections: 16
  maxIdleConnections: 4
  maxLifetime: 30s

redis:
  host: redis
  port: 6379
  password: ""
  db: 1
  connectTimeout: 5s
  readTimeout: 30s
  writeTimeout: 30s
  idleTimeout: 60s

aaa:
  url:
    base: "http://aaa:8060"
    getUsers: "/internal/user/list"
  redis:
    address: redis:6379
    password: ""
    db: 0
    connectTimeout: 5s
    readTimeout: 0 # 0 means infinity read
    writeTimeout: 30s
    idleTimeout: 60s
    maxIdle: 1
    maxActive: 10

jaeger:
  endpoint: "jaeger:6831"

openvidu:
  url:
    base: "http://openvidu-server:5443"
  user: "OPENVIDUAPP"
  password: "MY_SECRET"