version: '3.7'

services:
  chat:
    image: nkonev/chat:changing
    networks:
      backend:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.chat-service.loadbalancer.server.port=1235"
        - "traefik.http.routers.chat-router.rule=PathPrefix(`/api/chat`)"
        - "traefik.http.routers.chat-router.entrypoints=http"
        - "traefik.http.routers.chat-router.middlewares=auth-middleware@file,api-strip-prefix-middleware@file,retry-middleware@file"

        - "traefik.http.routers.blog-router.rule=PathPrefix(`/api/blog`)"
        - "traefik.http.routers.blog-router.entrypoints=http"
        - "traefik.http.routers.blog-router.middlewares=api-strip-prefix-middleware@file,retry-middleware@file"

        - "traefik.http.routers.chat-public-router.rule=PathPrefix(`/api/chat/public`)"
        - "traefik.http.routers.chat-public-router.entrypoints=http"
        - "traefik.http.routers.chat-public-router.middlewares=api-strip-prefix-middleware@file,retry-middleware@file"

        - "traefik.http.middlewares.chat-stripprefix-middleware.stripprefix.prefixes=/chat"
        - "traefik.http.routers.chat-version-router.rule=Path(`/chat/git.json`)"
        - "traefik.http.routers.chat-version-router.entrypoints=http"
        - "traefik.http.routers.chat-version-router.middlewares=chat-stripprefix-middleware"

    environment:
      - CHAT_POSTGRESQL.URL=postgres://chat:chatPazZw0rd@postgresql:5432/chat?sslmode=disable&application_name=chat-app
      - CHAT_SERVER.BODY.LIMIT=100G
      - CHAT_AAA.URL.BASE=http://aaa:8060
      - CHAT_RABBITMQ.URL=amqp://videoChat:videoChatPazZw0rd@rabbitmq:5672
      - CHAT_JAEGER.HOST=jaeger
      - CHAT_JAEGER.PORT=6831
      - CHAT_BASEURL=http://api.site.local:8080
      - CHAT_MESSAGE.ALLOWEDMEDIAURLS=http://api.site.local:8080,
      - CHAT_MESSAGE.ALLOWEDIFRAMEURLS=https://www.youtube.com,https://coub.com,https://vk.com,https://rutube.ru
      - CHAT_ONLYADMINCANCREATEBLOG=false

    logging:
      driver: "journald"
      options:
        tag: chat

networks:
  backend:
    driver: overlay
