log:
  v: 2

server:
  addr: ":7001"
  metricsAddr: ":8101"


sfu:
# Ballast size in MiB, will allocate memory to reduce the GC trigger upto 2x the
# size of ballast. Be aware that the ballast should be less than the half of memory
# available.
  ballast: 512
# enable prometheus sfu statistics
  withstats: false

router:
# Limit the remb bandwidth in kbps
# zero means no limits
  maxbandwidth: 1500
# max number of video tracks packets the SFU will keep trac
  maxpackettrack: 100
# Sets the audio level volume threshold.
# Values from [0-127] where 0 is the loudest.
# Audio levels are read from rtp extension header according to:
# https://tools.ietf.org/html/rfc6464
  audiolevelthreshold: 40
# Sets the interval in which the SFU will check the audio level
# in [ms]. If the active speaker has changed, the sfu will
# emit an event to clients.
  audiolevelinterval: 200
# Sets minimum percentage of events required to fire an audio level
# according to the expected events from the audiolevelinterval,
# calculated as audiolevelinterval/packetization time (20ms for 8kHz)
# Values from [0-100]
  audiolevelfilter: 10

  simulcast:
# Prefer best quality initially
    bestqualityfirst: true
# EXPERIMENTAL enable temporal layer change is currently an experimental feature,
# enable only for testing.
    enabletemporallayer: false

webrtc:
  singleport: 5000
# Range of ports that ion accepts WebRTC traffic on
# Format: [min, max]   and max - min >= 100
#  portrange: [5000, 5100]
# if sfu behind nat, set iceserver
# iceserver:
#   urls: ["stun:stun.stunprotocol.org:3478"]
  iceserver:
#    - urls: ["stun:stun.l.google.com:19302"]
    - urls: ["turn:api.site.local:3478"]
      username: "InternalUserNamE" # keep in secret
      credential: "SeCrEt"

# sdp semantics:
# "unified-plan"
# "plan-b"
# "unified-plan-with-fallback"
  sdpsemantics: "unified-plan-with-fallback"
# toggle multicast dns support: https://tools.ietf.org/html/draft-mdns-ice-candidates-00
  mdns: true

#  timeouts:
    # The duration in [sec] without network activity before a ICE Agent is considered disconnected
#    disconnected: 5
    # The duration in [sec] without network activity before a ICE Agent is considered failed after disconnected
#    failed: 25
    # # How often in [sec] the ICE Agent sends extra traffic if there is no activity, if media is flowing no traffic will be sent
#    keepalive: 2

  candidates:
# In case you're deploying ion-sfu on a server which is configured with
# a 1:1 NAT (e.g., Amazon EC2), you might want to also specify the public
# address of the machine using the setting below. This will result in
# all host candidates (which normally have a private IP address) to
# be rewritten with the public address provided in the settings. As
# such, use the option with caution and only if you know what you're doing.
# Multiple public IP addresses can be specified as a comma separated list
# if the sfu is deployed in a DMZ between two 1-1 NAT for internal and
# external users.
    nat1to1: ["1.2.3.4"]
    # https://stackoverflow.com/questions/35488252/ice-lite-on-android-webrtc/35566654#35566654
    icelite: true

turn:
# Enables embeded turn server
  enabled: true
# Sets the realm for turn server
  realm: "ion"
# The address the TURN server will listen on.
  address: "0.0.0.0:3478"
# Certs path to config tls/dtls
# cert="path/to/cert.pem"
# key="path/to/key.pem"
  portrange: [5200, 5300]
  auth:
# Use an auth secret to generate long(short)-term credentials defined in RFC5389-10.2
    secret: "secretAwsome"
# Sets the permanent credentials pairs
    credentials: "InternalUserNamE=SeCrEt"


chat:
  url:
    base: "http://chat:1235"

frontend:
  preferredCodec: h264
  simulcast: false
  simulcastLayers: ['low', 'high']
  resolution: vga
  forceKickAfter: 5s
  iceserver:
    - server:
        urls: ["turn:api.site.local:3478"]
      turnCredentialDuration: '168h'

rabbitmq:
  url: "amqp://videoChat:videoChatPazZw0rd@rabbitmq:5672"

